<!DOCTYPE html>
<html lang="en">
<head>
<a href="pocetnastranica.php" class="izbornik">POCETNA</a>
<a href="izvori.php" class="izbornik">IZVORI</a>
<a href="popiszanrova.php" class="izbornik">POPIS ZANROVA</a>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MUSICPEDIA</title>
      <link rel="stylesheet" href="CSS/izgledstranica.css">

</head>
<h1><b>MUSICPEDIA</b></h1>
<body>
   <h2><b>>Billie Holiday</b></h2>
   <p>Billie Holiday, rođena 7. travnja 1915. u Philadelphiji, Pennsylvania, bila je superzvijezda svog vremena. Prvi put se istaknula 1930-ih s jedinstvenim stilom koji je reinventirao konvencije modernog pjevanja i izvedbe. Više od 80 godina nakon što je snimila svoju prvu snimku, Billieino nasljeđe i dalje utjelovljuje ono što je elegantno i cool u suvremenoj glazbi. Holidayin komplicirani život i njezina autobiografija "Lady Sings the Blues" koja je definirala žanr učinili su je kulturnom ikonom. Evokativni, soulful glas koji je hrabro iznosila kao snagu dobra pretvarao je svaku pjesmu koju je pjevala u njezinu vlastitu. Danas se Billie Holiday pamti po svojim glazbenim remek-djelima, vještinama pisanja pjesama, kreativnosti i hrabrim stavovima o nejednakosti i pravdi.</p>
    <img src="Billy Holiday.jpg" alt="Billy Holiday" class="slika-benda">
   <h3>Najpoznatiji albumi:</h3>
<ol>
    <li>LADY SINGS THE BLUES (1956)</li>
    <li>BILLIE HOLIDAY SINGS (1952)</li>
    <li> MUSIC FOR TORCHING (1955)</li>
    <li>LADY IN SATIN (1958)</li>
    <li>ALL OR NOTHING AT ALL (1958)</li>
</ol>
<h4>Najpoznatije pjesme:</h4>
<ol>
<li>Strange Fruit</li>
<li> I'll Be Seeing You</li>
<li>Solitude</li>
<li>Blue Moon</li>
<li>Lover Man</li>
</ol>
<h5>Video:</h5>
<p><iframe width="951" height="535" src="https://www.youtube.com/embed/aDglmrJQNQ8" title="Billie Holiday &quot;The 25 best songs&quot; GR 073/15 (Full Album)" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></p>
</body>
</html>